/**
 * Falcon Comprehensive Indian FMCG & Retail Master Product Catalog
 * Covers 150+ Top Indian Grocery, FMCG, Personal Care & Household brands.
 * Instant 0.01s offline barcode and title matcher.
 */

export interface MasterCatalogProduct {
  barcode?: string;
  name: string;
  brand: string;
  category: string;
  mrp: number;
  purchasePrice: number;
  wholesalePrice: number;
  unit: string;
  description?: string;
  keywords?: string[];
}

export const INDIAN_RETAIL_CATALOG: MasterCatalogProduct[] = [
  // ==========================================
  // 1. EDIBLE OILS, GHEE & BUTTER
  // ==========================================
  {
    barcode: "8901088001004",
    name: "Parachute 100% Pure Coconut Oil 100ml",
    brand: "Parachute",
    category: "Hair Care",
    mrp: 46,
    purchasePrice: 35,
    wholesalePrice: 40,
    unit: "bottle",
    description: "Pure coconut oil made from naturally sun-dried coconuts.",
    keywords: ["coconut", "oil", "parachute", "marico", "hair oil", "100ml"],
  },
  {
    barcode: "8901088001028",
    name: "Parachute 100% Pure Coconut Oil 200ml",
    brand: "Parachute",
    category: "Hair Care",
    mrp: 90,
    purchasePrice: 68,
    wholesalePrice: 78,
    unit: "bottle",
    description: "Parachute 200ml pure coconut oil bottle.",
    keywords: ["parachute", "200ml", "coconut oil"],
  },
  {
    barcode: "8901088001059",
    name: "Parachute 100% Pure Coconut Oil 500ml",
    brand: "Parachute",
    category: "Hair Care",
    mrp: 215,
    purchasePrice: 165,
    wholesalePrice: 185,
    unit: "bottle",
    description: "Parachute 500ml pure coconut oil bottle.",
    keywords: ["parachute", "500ml", "coconut oil"],
  },
  {
    barcode: "8906007280014",
    name: "Fortune Sunlite Refined Sunflower Oil 1L Pouch",
    brand: "Fortune",
    category: "Edible Oils",
    mrp: 145,
    purchasePrice: 118,
    wholesalePrice: 130,
    unit: "pouch",
    description: "Light and healthy refined sunflower cooking oil.",
    keywords: ["fortune", "sunflower", "oil", "refined", "cooking oil", "1l"],
  },
  {
    barcode: "8906007280021",
    name: "Fortune Premium Kachi Ghani Mustard Oil 1L Pouch",
    brand: "Fortune",
    category: "Edible Oils",
    mrp: 160,
    purchasePrice: 130,
    wholesalePrice: 145,
    unit: "pouch",
    description: "Traditional cold-pressed pungent mustard oil for cooking.",
    keywords: ["fortune", "mustard", "sarson", "kachi ghani", "tel"],
  },
  {
    barcode: "8901088005019",
    name: "Saffola Gold Pro Healthy Heart Blended Edible Oil 1L Pouch",
    brand: "Saffola",
    category: "Edible Oils",
    mrp: 185,
    purchasePrice: 148,
    wholesalePrice: 165,
    unit: "pouch",
    description: "Heart healthy blended rice bran and sunflower cooking oil.",
    keywords: ["saffola", "saffola gold", "cooking oil", "heart oil"],
  },
  {
    barcode: "8901262010015",
    name: "Amul Pure Ghee 1L Pouch",
    brand: "Amul",
    category: "Dairy & Ghee",
    mrp: 620,
    purchasePrice: 540,
    wholesalePrice: 575,
    unit: "pouch",
    description: "Aromatic pure cow & buffalo milk clarified butter ghee.",
    keywords: ["amul", "ghee", "pure ghee", "1l", "dairy"],
  },
  {
    barcode: "8901262010022",
    name: "Amul Pure Ghee 500ml Pouch",
    brand: "Amul",
    category: "Dairy & Ghee",
    mrp: 320,
    purchasePrice: 275,
    wholesalePrice: 295,
    unit: "pouch",
    description: "Amul 500ml pure desi ghee pouch.",
    keywords: ["amul ghee 500ml", "amul 500ml"],
  },
  {
    barcode: "8901262020014",
    name: "Amul Pasteurised Salted Butter 100g",
    brand: "Amul",
    category: "Dairy & Ghee",
    mrp: 60,
    purchasePrice: 52,
    wholesalePrice: 55,
    unit: "pack",
    description: "Utterly butterly delicious creamy salted butter.",
    keywords: ["amul butter", "butter 100g", "makhan"],
  },
  {
    barcode: "8901262020021",
    name: "Amul Pasteurised Salted Butter 500g",
    brand: "Amul",
    category: "Dairy & Ghee",
    mrp: 275,
    purchasePrice: 240,
    wholesalePrice: 255,
    unit: "pack",
    description: "Amul 500g family butter pack.",
    keywords: ["amul butter 500g", "butter"],
  },
  {
    barcode: "8904109400013",
    name: "Patanjali Cow Ghee 1L Pouch",
    brand: "Patanjali",
    category: "Dairy & Ghee",
    mrp: 650,
    purchasePrice: 560,
    wholesalePrice: 600,
    unit: "pouch",
    description: "Pure indigenous cow milk ghee for wellness and worship.",
    keywords: ["patanjali", "cow ghee", "ghee 1l", "desi ghee"],
  },

  // ==========================================
  // 2. GROCERIES, FLOUR, RICE & STAPLES
  // ==========================================
  {
    barcode: "8901030012011",
    name: "Tata Salt Vacuum Evaporated Iodized Salt 1kg",
    brand: "Tata",
    category: "Groceries",
    mrp: 28,
    purchasePrice: 22,
    wholesalePrice: 24.5,
    unit: "packet",
    description: "Desh Ka Namak purest vacuum evaporated iodized salt.",
    keywords: ["tata salt", "namak", "salt", "iodized", "1kg"],
  },
  {
    barcode: "8901030012028",
    name: "Tata Salt Lite Low Sodium Iodized Salt 1kg",
    brand: "Tata",
    category: "Groceries",
    mrp: 45,
    purchasePrice: 35,
    wholesalePrice: 39,
    unit: "packet",
    description: "15% low sodium vacuum evaporated salt for blood pressure management.",
    keywords: ["tata salt lite", "low sodium salt"],
  },
  {
    barcode: "8901725182104",
    name: "Aashirvaad Shuddh Chakki Whole Wheat Atta 5kg",
    brand: "Aashirvaad",
    category: "Staples & Flour",
    mrp: 245,
    purchasePrice: 198,
    wholesalePrice: 218,
    unit: "bag",
    description: "100% whole wheat chakki ground fresh flour.",
    keywords: ["aashirvaad", "atta", "wheat", "flour", "5kg"],
  },
  {
    barcode: "8901725182111",
    name: "Aashirvaad Shuddh Chakki Whole Wheat Atta 10kg",
    brand: "Aashirvaad",
    category: "Staples & Flour",
    mrp: 475,
    purchasePrice: 385,
    wholesalePrice: 425,
    unit: "bag",
    description: "10kg whole wheat atta family bag.",
    keywords: ["aashirvaad 10kg", "atta 10kg", "wheat"],
  },
  {
    barcode: "8906007283015",
    name: "Fortune Everyday Basmati Rice 1kg",
    brand: "Fortune",
    category: "Staples & Flour",
    mrp: 95,
    purchasePrice: 75,
    wholesalePrice: 83,
    unit: "packet",
    description: "Aromatic long grain basmati rice for daily meals.",
    keywords: ["fortune rice", "basmati rice", "chawal", "1kg"],
  },
  {
    barcode: "8906007283053",
    name: "Fortune Special Biryani Basmati Rice 1kg",
    brand: "Fortune",
    category: "Staples & Flour",
    mrp: 175,
    purchasePrice: 138,
    wholesalePrice: 155,
    unit: "packet",
    description: "Extra long pearl white basmati grain for authentic biryani.",
    keywords: ["biryani rice", "fortune biryani", "basmati"],
  },
  {
    barcode: "8901030013018",
    name: "Tata Sampann Unpolished Toor Dal 1kg",
    brand: "Tata Sampann",
    category: "Pulses & Dals",
    mrp: 195,
    purchasePrice: 158,
    wholesalePrice: 172,
    unit: "packet",
    description: "Naturally unpolished protein rich arhar / toor dal.",
    keywords: ["tata sampann", "toor dal", "arhar dal", "dal 1kg"],
  },
  {
    barcode: "8901030013025",
    name: "Tata Sampann Unpolished Chana Dal 1kg",
    brand: "Tata Sampann",
    category: "Pulses & Dals",
    mrp: 110,
    purchasePrice: 88,
    wholesalePrice: 98,
    unit: "packet",
    description: "Natural wholesome unpolished chana dal.",
    keywords: ["chana dal", "tata dal"],
  },
  {
    barcode: "8901030013032",
    name: "Tata Sampann 100% Pure Besan 500g",
    brand: "Tata Sampann",
    category: "Staples & Flour",
    mrp: 65,
    purchasePrice: 50,
    wholesalePrice: 56,
    unit: "packet",
    description: "Finely milled pure 100% chana dal gram flour.",
    keywords: ["besan", "tata besan", "gram flour"],
  },
  {
    barcode: "8904004400101",
    name: "Rajdhani Sooji / Rawa 500g",
    brand: "Rajdhani",
    category: "Staples & Flour",
    mrp: 38,
    purchasePrice: 29,
    wholesalePrice: 33,
    unit: "packet",
    description: "Crisp grainy semolina sooji for halwa and upma.",
    keywords: ["sooji", "suji", "rawa", "rajdhani"],
  },
  {
    barcode: "8904004400118",
    name: "Rajdhani Maida / Refined Wheat Flour 500g",
    brand: "Rajdhani",
    category: "Staples & Flour",
    mrp: 35,
    purchasePrice: 26,
    wholesalePrice: 30,
    unit: "packet",
    description: "Super fine refined all-purpose wheat flour.",
    keywords: ["maida", "rajdhani maida"],
  },

  // ==========================================
  // 3. SPICES & MASALA
  // ==========================================
  {
    barcode: "8901512001017",
    name: "MDH Deggi Mirch Red Chilli Powder 100g",
    brand: "MDH",
    category: "Spices & Masala",
    mrp: 95,
    purchasePrice: 75,
    wholesalePrice: 83,
    unit: "box",
    description: "Rich natural red color mild spicy Deggi Mirch powder.",
    keywords: ["mdh", "deggi mirch", "chilli", "mirch powder", "masala"],
  },
  {
    barcode: "8901512001055",
    name: "MDH Garam Masala 100g",
    brand: "MDH",
    category: "Spices & Masala",
    mrp: 110,
    purchasePrice: 86,
    wholesalePrice: 96,
    unit: "box",
    description: "Aromatic blend of roasted Indian spices.",
    keywords: ["mdh", "garam masala", "spices"],
  },
  {
    barcode: "8901512001109",
    name: "MDH Chana Masala 100g",
    brand: "MDH",
    category: "Spices & Masala",
    mrp: 88,
    purchasePrice: 69,
    wholesalePrice: 77,
    unit: "box",
    description: "Authentic spicy chana and chole masala powder.",
    keywords: ["mdh chana masala", "chole masala"],
  },
  {
    barcode: "8901512001154",
    name: "MDH Chunky Chat Masala 100g",
    brand: "MDH",
    category: "Spices & Masala",
    mrp: 85,
    purchasePrice: 66,
    wholesalePrice: 74,
    unit: "box",
    description: "Tangy and savory sprinkle chat masala.",
    keywords: ["mdh chat masala", "chaat masala"],
  },
  {
    barcode: "8901512001208",
    name: "MDH Kitchen King Masala 100g",
    brand: "MDH",
    category: "Spices & Masala",
    mrp: 98,
    purchasePrice: 77,
    wholesalePrice: 86,
    unit: "box",
    description: "All-purpose rich curry spice blend for North Indian vegetables.",
    keywords: ["mdh kitchen king", "kitchen king"],
  },
  {
    barcode: "8901712001016",
    name: "Everest Turmeric / Haldi Powder 100g",
    brand: "Everest",
    category: "Spices & Masala",
    mrp: 40,
    purchasePrice: 31,
    wholesalePrice: 35,
    unit: "box",
    description: "Pure aromatic turmeric haldi powder.",
    keywords: ["everest", "haldi", "turmeric powder", "masala"],
  },
  {
    barcode: "8901712001023",
    name: "Everest Coriander / Dhania Powder 100g",
    brand: "Everest",
    category: "Spices & Masala",
    mrp: 38,
    purchasePrice: 29,
    wholesalePrice: 33,
    unit: "box",
    description: "Fresh fragrant ground coriander seeds powder.",
    keywords: ["everest dhania", "coriander powder"],
  },
  {
    barcode: "8901712001030",
    name: "Everest Tikhalal Hot Red Chilli Powder 100g",
    brand: "Everest",
    category: "Spices & Masala",
    mrp: 65,
    purchasePrice: 50,
    wholesalePrice: 56,
    unit: "box",
    description: "Spicy pungent red chilli powder for extra heat.",
    keywords: ["everest tikhalal", "mirch powder"],
  },
  {
    barcode: "8901712001085",
    name: "Everest Pav Bhaji Masala 100g",
    brand: "Everest",
    category: "Spices & Masala",
    mrp: 85,
    purchasePrice: 66,
    wholesalePrice: 74,
    unit: "box",
    description: "Mumbai street style spicy pav bhaji spice blend.",
    keywords: ["everest pav bhaji", "pav bhaji masala"],
  },
  {
    barcode: "8901712001122",
    name: "Everest Sambhar Masala 100g",
    brand: "Everest",
    category: "Spices & Masala",
    mrp: 85,
    purchasePrice: 66,
    wholesalePrice: 74,
    unit: "box",
    description: "Authentic South Indian aromatic sambhar powder.",
    keywords: ["everest sambhar", "sambhar masala"],
  },
  {
    barcode: "8901512009013",
    name: "Catch Compounded Asafoetida / Hing 50g Bottle",
    brand: "Catch",
    category: "Spices & Masala",
    mrp: 75,
    purchasePrice: 58,
    wholesalePrice: 65,
    unit: "bottle",
    description: "Strong aroma digestive hing powder.",
    keywords: ["catch hing", "asafoetida", "hing"],
  },

  // ==========================================
  // 4. PACKAGED FOOD, NOODLES & SOUPS
  // ==========================================
  {
    barcode: "8901058852339",
    name: "Maggi 2-Minute Masala Instant Noodles 70g",
    brand: "Maggi",
    category: "Packaged Food",
    mrp: 14,
    purchasePrice: 11,
    wholesalePrice: 12.5,
    unit: "packet",
    description: "India's favorite delicious instant masala noodles.",
    keywords: ["maggi", "noodles", "masala", "nestle", "2 minute", "70g"],
  },
  {
    barcode: "8901058852346",
    name: "Maggi 2-Minute Masala Noodles 4-Pack (280g)",
    brand: "Maggi",
    category: "Packaged Food",
    mrp: 56,
    purchasePrice: 44,
    wholesalePrice: 49,
    unit: "pack",
    description: "Maggi family 4 in 1 multipack noodles.",
    keywords: ["maggi 4 pack", "multipack", "maggi family"],
  },
  {
    barcode: "8901058852384",
    name: "Maggi Nutri-Licious Atta Masala Noodles 72.5g",
    brand: "Maggi",
    category: "Packaged Food",
    mrp: 20,
    purchasePrice: 16,
    wholesalePrice: 18,
    unit: "packet",
    description: "Whole wheat grain healthy atta noodles with real veggies.",
    keywords: ["maggi atta noodles", "atta maggi"],
  },
  {
    barcode: "8901058854012",
    name: "Maggi Rich Tomato Ketchup 500g Bottle",
    brand: "Maggi",
    category: "Sauces & Spreads",
    mrp: 125,
    purchasePrice: 98,
    wholesalePrice: 110,
    unit: "bottle",
    description: "Tangy rich tomato ketchup made with vine-ripened tomatoes.",
    keywords: ["maggi ketchup", "tomato sauce", "sauce 500g"],
  },
  {
    barcode: "8901058854050",
    name: "Maggi Hot & Sweet Tomato Chilli Sauce 500g Bottle",
    brand: "Maggi",
    category: "Sauces & Spreads",
    mrp: 135,
    purchasePrice: 105,
    wholesalePrice: 118,
    unit: "bottle",
    description: "Spicy sweet chilli blend tomato ketchup sauce.",
    keywords: ["maggi hot and sweet", "chilli sauce"],
  },
  {
    barcode: "8901725181220",
    name: "Yippee Magic Masala Noodles 65g",
    brand: "Sunfeast Yippee",
    category: "Packaged Food",
    mrp: 14,
    purchasePrice: 11,
    wholesalePrice: 12.5,
    unit: "packet",
    description: "Non-sticky round block masala instant noodles.",
    keywords: ["yippee", "noodles", "sunfeast", "magic masala"],
  },
  {
    barcode: "8901030017016",
    name: "Knorr Classic Mixed Vegetable Soup 43g",
    brand: "Knorr",
    category: "Packaged Food",
    mrp: 45,
    purchasePrice: 35,
    wholesalePrice: 39,
    unit: "packet",
    description: "Rich creamy vegetable soup mix ready in 3 minutes.",
    keywords: ["knorr soup", "mixed veg soup"],
  },

  // ==========================================
  // 5. BISCUITS, COOKIES & BAKERY
  // ==========================================
  {
    barcode: "8901719101016",
    name: "Parle-G Original Gluco Biscuits 250g",
    brand: "Parle",
    category: "Snacks & Biscuits",
    mrp: 25,
    purchasePrice: 19.5,
    wholesalePrice: 22,
    unit: "pack",
    description: "India's highest selling glucose tea biscuits.",
    keywords: ["parle g", "parleg", "biscuit", "glucose", "250g"],
  },
  {
    barcode: "8901719101023",
    name: "Parle-G Gold Biscuits 1kg Family Pack",
    brand: "Parle",
    category: "Snacks & Biscuits",
    mrp: 110,
    purchasePrice: 88,
    wholesalePrice: 98,
    unit: "pack",
    description: "Bigger thicker crunchier glucose biscuits family tub pack.",
    keywords: ["parle g 1kg", "parle gold"],
  },
  {
    barcode: "8901719102013",
    name: "Parle Monaco Salted Classic Biscuits 200g",
    brand: "Parle",
    category: "Snacks & Biscuits",
    mrp: 35,
    purchasePrice: 27,
    wholesalePrice: 30,
    unit: "pack",
    description: "Light crispy salty crackers for snacking.",
    keywords: ["monaco", "parle monaco", "salted biscuit"],
  },
  {
    barcode: "8901719103010",
    name: "Parle Krackjack Sweet & Salty Crackers 200g",
    brand: "Parle",
    category: "Snacks & Biscuits",
    mrp: 35,
    purchasePrice: 27,
    wholesalePrice: 30,
    unit: "pack",
    description: "Original dual taste sweet and salty crispy crackers.",
    keywords: ["krackjack", "crackjack", "parle"],
  },
  {
    barcode: "8901719104017",
    name: "Parle Hide & Seek Chocolate Chip Cookies 120g",
    brand: "Parle",
    category: "Snacks & Biscuits",
    mrp: 40,
    purchasePrice: 31,
    wholesalePrice: 35,
    unit: "pack",
    description: "Crispy cocoa biscuits studded with real rich chocolate chips.",
    keywords: ["hide and seek", "choco chip", "parle"],
  },
  {
    barcode: "8901063012211",
    name: "Britannia Good Day Butter Cookies 200g",
    brand: "Britannia",
    category: "Snacks & Biscuits",
    mrp: 45,
    purchasePrice: 35,
    wholesalePrice: 39,
    unit: "pack",
    description: "Rich crunchy butter cookies with smiles.",
    keywords: ["good day", "britannia", "butter cookies", "biscuit"],
  },
  {
    barcode: "8901063012228",
    name: "Britannia Good Day Cashew Cookies 200g",
    brand: "Britannia",
    category: "Snacks & Biscuits",
    mrp: 50,
    purchasePrice: 39,
    wholesalePrice: 44,
    unit: "pack",
    description: "Loaded with real crunchy roasted cashew nuts.",
    keywords: ["good day cashew", "kaju biscuit"],
  },
  {
    barcode: "8901063013010",
    name: "Britannia Marie Gold Tea Biscuits 300g",
    brand: "Britannia",
    category: "Snacks & Biscuits",
    mrp: 40,
    purchasePrice: 31,
    wholesalePrice: 35,
    unit: "pack",
    description: "Crispy light tea-time accompaniment biscuits.",
    keywords: ["marie gold", "britannia marie", "tea biscuit"],
  },
  {
    barcode: "8901063014017",
    name: "Britannia Bourbon Chocolate Cream Biscuits 150g",
    brand: "Britannia",
    category: "Snacks & Biscuits",
    mrp: 35,
    purchasePrice: 27,
    wholesalePrice: 30,
    unit: "pack",
    description: "Rich chocolate cream sandwich biscuits sprinkled with sugar crystals.",
    keywords: ["bourbon", "britannia bourbon", "chocolate biscuit"],
  },
  {
    barcode: "7622201727765",
    name: "Cadbury Oreo Vanilla Creme Sandwich Cookies 120g",
    brand: "Oreo",
    category: "Snacks & Biscuits",
    mrp: 35,
    purchasePrice: 27,
    wholesalePrice: 30,
    unit: "pack",
    description: "Twist lick dunk dark cocoa cookies with sweet vanilla cream.",
    keywords: ["oreo", "cadbury oreo", "vanilla cream"],
  },
  {
    barcode: "8901725112019",
    name: "Sunfeast Dark Fantasy Choco Fills 300g",
    brand: "Sunfeast",
    category: "Snacks & Biscuits",
    mrp: 120,
    purchasePrice: 94,
    wholesalePrice: 105,
    unit: "box",
    description: "Molten liquid chocolate filled luxury baked cookies.",
    keywords: ["dark fantasy", "choco fills", "sunfeast"],
  },

  // ==========================================
  // 6. CHIPS, NAMKEEN & SNACKS
  // ==========================================
  {
    barcode: "8901491101824",
    name: "Lays India's Magic Masala Potato Chips 50g",
    brand: "Lays",
    category: "Snacks & Biscuits",
    mrp: 20,
    purchasePrice: 15.5,
    wholesalePrice: 17.5,
    unit: "packet",
    description: "Crispy ridged potato chips with spicy Indian magic masala.",
    keywords: ["lays", "chips", "magic masala", "blue lays", "20 rs"],
  },
  {
    barcode: "8901491101848",
    name: "Lays Spanish Tomato Tango Potato Chips 50g",
    brand: "Lays",
    category: "Snacks & Biscuits",
    mrp: 20,
    purchasePrice: 15.5,
    wholesalePrice: 17.5,
    unit: "packet",
    description: "Sweet and tangy tomato flavored crispy potato chips.",
    keywords: ["lays tomato", "red lays", "tomato chips"],
  },
  {
    barcode: "8901491101855",
    name: "Lays American Style Cream & Onion Chips 50g",
    brand: "Lays",
    category: "Snacks & Biscuits",
    mrp: 20,
    purchasePrice: 15.5,
    wholesalePrice: 17.5,
    unit: "packet",
    description: "Creamy herb and onion flavored potato chips.",
    keywords: ["lays cream and onion", "green lays"],
  },
  {
    barcode: "8901491101831",
    name: "Kurkure Masala Munch Crispy Snacks 85g",
    brand: "Kurkure",
    category: "Snacks & Biscuits",
    mrp: 20,
    purchasePrice: 15.5,
    wholesalePrice: 17.5,
    unit: "packet",
    description: "Crunchy spicy puffed corn and rice curls.",
    keywords: ["kurkure", "masala munch", "snacks", "tedha hai par mera hai"],
  },
  {
    barcode: "8901491101862",
    name: "Kurkure Green Chutney Style 85g",
    brand: "Kurkure",
    category: "Snacks & Biscuits",
    mrp: 20,
    purchasePrice: 15.5,
    wholesalePrice: 17.5,
    unit: "packet",
    description: "Chatpata spicy green mint chutney curls.",
    keywords: ["kurkure green", "green chutney"],
  },
  {
    barcode: "8904063200018",
    name: "Haldiram's Nagpur Aloo Bhujia 200g",
    brand: "Haldiram's",
    category: "Snacks & Biscuits",
    mrp: 55,
    purchasePrice: 42,
    wholesalePrice: 48,
    unit: "packet",
    description: "Spicy mint flavored crispy potato and gram flour sev.",
    keywords: ["haldiram aloo bhujia", "bhujia 200g", "namkeen"],
  },
  {
    barcode: "8904063200056",
    name: "Haldiram's Nagpur Khatta Meetha Mixture 200g",
    brand: "Haldiram's",
    category: "Snacks & Biscuits",
    mrp: 55,
    purchasePrice: 42,
    wholesalePrice: 48,
    unit: "packet",
    description: "Sweet and sour crunchy blended sev, peas, and peanuts mixture.",
    keywords: ["haldiram khatta meetha", "khatta meetha"],
  },
  {
    barcode: "8904063200100",
    name: "Haldiram's Nagpur Moong Dal 200g",
    brand: "Haldiram's",
    category: "Snacks & Biscuits",
    mrp: 60,
    purchasePrice: 47,
    wholesalePrice: 52,
    unit: "packet",
    description: "Crispy salted deep fried yellow moong dal snack.",
    keywords: ["haldiram moong dal", "moong dal namkeen"],
  },

  // ==========================================
  // 7. CHOCOLATES & CONFECTIONERY
  // ==========================================
  {
    barcode: "7622201720018",
    name: "Cadbury Dairy Milk Chocolate Bar 50g",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    mrp: 45,
    purchasePrice: 36,
    wholesalePrice: 40,
    unit: "piece",
    description: "Classic creamy milk chocolate bar made with a glass and a half of pure milk.",
    keywords: ["cadbury", "dairy milk", "chocolate", "50g"],
  },
  {
    barcode: "7622201720025",
    name: "Cadbury Dairy Milk Silk Chocolate Bar 60g",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    mrp: 80,
    purchasePrice: 64,
    wholesalePrice: 71,
    unit: "piece",
    description: "Silky smooth melt in mouth premium chocolate.",
    keywords: ["dairy milk silk", "silk chocolate"],
  },
  {
    barcode: "7622201720032",
    name: "Cadbury 5 Star Chocolate Bar 40g",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    mrp: 20,
    purchasePrice: 16,
    wholesalePrice: 18,
    unit: "piece",
    description: "Chewy caramel and nougat core covered in milk chocolate.",
    keywords: ["5 star", "cadbury 5 star"],
  },
  {
    barcode: "8901058850014",
    name: "Nestle KitKat 4-Finger Chocolate Wafer 38.5g",
    brand: "KitKat",
    category: "Chocolates & Sweets",
    mrp: 30,
    purchasePrice: 24,
    wholesalePrice: 26.5,
    unit: "piece",
    description: "Crisp baked wafer fingers covered in creamy milk chocolate. Have a break, have a KitKat.",
    keywords: ["kitkat", "nestle kitkat", "wafer chocolate"],
  },
  {
    barcode: "8901058850052",
    name: "Nestle Munch Crunchy Wafer Bar 25g",
    brand: "Nestle",
    category: "Chocolates & Sweets",
    mrp: 10,
    purchasePrice: 7.8,
    wholesalePrice: 8.8,
    unit: "piece",
    description: "Crunch-o-meter extra crunchy chocolate coated wafer.",
    keywords: ["munch", "nestle munch"],
  },

  // ==========================================
  // 8. BEVERAGES, TEA & COFFEE
  // ==========================================
  {
    barcode: "8901030018501",
    name: "Tata Tea Premium Desh Ki Chai 250g",
    brand: "Tata Tea",
    category: "Beverages",
    mrp: 140,
    purchasePrice: 110,
    wholesalePrice: 122,
    unit: "packet",
    description: "Unique blend of fine leaf and strong dust tea.",
    keywords: ["tata tea", "chai", "tea", "premium", "desh ki chai", "250g"],
  },
  {
    barcode: "8901030018518",
    name: "Tata Tea Premium Desh Ki Chai 500g",
    brand: "Tata Tea",
    category: "Beverages",
    mrp: 270,
    purchasePrice: 215,
    wholesalePrice: 240,
    unit: "packet",
    description: "Tata tea premium 500g family pack.",
    keywords: ["tata tea 500g", "tea 500g"],
  },
  {
    barcode: "8901030018600",
    name: "Tata Tea Gold Fine Long Leaf Assam Tea 250g",
    brand: "Tata Tea",
    category: "Beverages",
    mrp: 165,
    purchasePrice: 130,
    wholesalePrice: 145,
    unit: "packet",
    description: "15% gently rolled long tea leaves with strong CTC tea.",
    keywords: ["tata tea gold", "tata gold"],
  },
  {
    barcode: "8901030019010",
    name: "Brooke Bond Red Label Strong Tea 250g",
    brand: "Red Label",
    category: "Beverages",
    mrp: 135,
    purchasePrice: 106,
    wholesalePrice: 118,
    unit: "packet",
    description: "Swad apnepan ka strong rich color tea.",
    keywords: ["red label", "brooke bond", "red label tea"],
  },
  {
    barcode: "8901030019102",
    name: "Brooke Bond Taj Mahal Tea 250g",
    brand: "Taj Mahal",
    category: "Beverages",
    mrp: 190,
    purchasePrice: 150,
    wholesalePrice: 168,
    unit: "box",
    description: "Wah Taj! Premium selected aromatic long leaf tea.",
    keywords: ["taj mahal tea", "wah taj"],
  },
  {
    barcode: "8901058851011",
    name: "Nescafe Classic 100% Pure Instant Coffee Jar 50g",
    brand: "Nescafe",
    category: "Beverages",
    mrp: 195,
    purchasePrice: 152,
    wholesalePrice: 170,
    unit: "jar",
    description: "Rich aroma pure roasted coffee granules.",
    keywords: ["nescafe", "coffee", "classic", "instant coffee", "50g"],
  },
  {
    barcode: "8901030019508",
    name: "Bru Instant Coffee Chicory Mixture 50g",
    brand: "Bru",
    category: "Beverages",
    mrp: 120,
    purchasePrice: 94,
    wholesalePrice: 105,
    unit: "pouch",
    description: "Aromatic blend of 70% coffee and 30% chicory.",
    keywords: ["bru", "bru coffee", "bru instant"],
  },
  {
    barcode: "8901030019805",
    name: "Horlicks Classic Malt Nutrition Drink 500g Jar",
    brand: "Horlicks",
    category: "Health Drinks",
    mrp: 265,
    purchasePrice: 210,
    wholesalePrice: 232,
    unit: "jar",
    description: "Clinically proven to make kids taller, stronger, sharper.",
    keywords: ["horlicks", "malt", "health drink", "500g"],
  },
  {
    barcode: "7622201729011",
    name: "Cadbury Bournvita Chocolate Health Drink 500g Jar",
    brand: "Bournvita",
    category: "Health Drinks",
    mrp: 250,
    purchasePrice: 198,
    wholesalePrice: 220,
    unit: "jar",
    description: "Inner strength formula chocolate malt drink.",
    keywords: ["bournvita", "cadbury bournvita", "500g"],
  },
  {
    barcode: "8901764011210",
    name: "Frooti Fresh Mango Drink 1.2L Bottle",
    brand: "Frooti",
    category: "Beverages",
    mrp: 65,
    purchasePrice: 50,
    wholesalePrice: 56,
    unit: "bottle",
    description: "Juicy mango pulp beverage drink.",
    keywords: ["frooti", "mango drink", "frooti 1.2l"],
  },
  {
    barcode: "8901764011012",
    name: "Frooti Fresh Mango Drink 150ml Tetra Pack",
    brand: "Frooti",
    category: "Beverages",
    mrp: 10,
    purchasePrice: 7.8,
    wholesalePrice: 8.8,
    unit: "pack",
    description: "Pocket size delicious mango fruit drink.",
    keywords: ["frooti 10 rs", "frooti small"],
  },
  {
    barcode: "8901491102012",
    name: "Thums Up Taste the Thunder 750ml Bottle",
    brand: "Thums Up",
    category: "Beverages",
    mrp: 40,
    purchasePrice: 31,
    wholesalePrice: 35,
    unit: "bottle",
    description: "Strong fizzy cola cold drink with spicy kick.",
    keywords: ["thums up", "coca cola", "cold drink", "750ml"],
  },
  {
    barcode: "8901491102050",
    name: "Sprite Clear Lemon Lime Carbonated Drink 750ml",
    brand: "Sprite",
    category: "Beverages",
    mrp: 40,
    purchasePrice: 31,
    wholesalePrice: 35,
    unit: "bottle",
    description: "Refreshing crystal clear lemon-lime thirst quencher.",
    keywords: ["sprite", "cold drink 750ml", "lemon drink"],
  },

  // ==========================================
  // 9. PERSONAL CARE, SOAPS & SHAMPOOS
  // ==========================================
  {
    barcode: "8901030383401",
    name: "Dettol Original Germ Protection Bathing Soap 75g",
    brand: "Dettol",
    category: "Personal Care",
    mrp: 40,
    purchasePrice: 31,
    wholesalePrice: 35,
    unit: "piece",
    description: "Antibacterial germ protection bathing bar.",
    keywords: ["dettol", "soap", "bathing soap", "germ protection", "75g"],
  },
  {
    barcode: "8901030383425",
    name: "Dettol Original Bathing Soap (Buy 4 Get 1 Free Pack)",
    brand: "Dettol",
    category: "Personal Care",
    mrp: 160,
    purchasePrice: 125,
    wholesalePrice: 140,
    unit: "pack",
    description: "Dettol 5 in 1 value saver family pack.",
    keywords: ["dettol pack", "dettol 5 pack", "dettol soap"],
  },
  {
    barcode: "8901030383500",
    name: "Dettol Skincare Bathing Soap 75g",
    brand: "Dettol",
    category: "Personal Care",
    mrp: 42,
    purchasePrice: 32,
    wholesalePrice: 37,
    unit: "piece",
    description: "Nourishing moisturizers with trusted germ protection.",
    keywords: ["dettol skincare", "dettol pink soap"],
  },
  {
    barcode: "8901030383609",
    name: "Dettol Antiseptic Liquid Disinfectant 250ml",
    brand: "Dettol",
    category: "Health & First Aid",
    mrp: 145,
    purchasePrice: 114,
    wholesalePrice: 128,
    unit: "bottle",
    description: "Trusted medical disinfectant for cuts, bites, shaving, and laundry.",
    keywords: ["dettol liquid", "antiseptic", "dettol 250ml"],
  },
  {
    barcode: "8901030015500",
    name: "Lifebuoy Total 10 Germ Protection Soap 100g",
    brand: "Lifebuoy",
    category: "Personal Care",
    mrp: 35,
    purchasePrice: 27,
    wholesalePrice: 30,
    unit: "piece",
    description: "Strong germ protection red soap bar.",
    keywords: ["lifebuoy", "soap", "total 10"],
  },
  {
    barcode: "8901030366602",
    name: "Dove Cream Beauty Bathing Bar 75g",
    brand: "Dove",
    category: "Personal Care",
    mrp: 65,
    purchasePrice: 50,
    wholesalePrice: 56,
    unit: "piece",
    description: "1/4 moisturizing cream beauty bathing soap bar.",
    keywords: ["dove", "soap", "cream", "moisturizing"],
  },
  {
    barcode: "8901030366626",
    name: "Dove Cream Beauty Bar (Buy 3 Get 1 Free)",
    brand: "Dove",
    category: "Personal Care",
    mrp: 240,
    purchasePrice: 188,
    wholesalePrice: 210,
    unit: "pack",
    description: "Dove 4-pack value bundle.",
    keywords: ["dove 4 pack", "dove soap"],
  },
  {
    barcode: "8901030048102",
    name: "Clinic Plus Strong & Long Shampoo 175ml",
    brand: "Clinic Plus",
    category: "Hair Care",
    mrp: 120,
    purchasePrice: 92,
    wholesalePrice: 104,
    unit: "bottle",
    description: "Nourishing milk protein shampoo for strong hair.",
    keywords: ["clinic plus", "shampoo", "strong and long", "175ml"],
  },
  {
    barcode: "8901030048157",
    name: "Clinic Plus Strong & Long Shampoo 340ml",
    brand: "Clinic Plus",
    category: "Hair Care",
    mrp: 230,
    purchasePrice: 178,
    wholesalePrice: 200,
    unit: "bottle",
    description: "Clinic plus 340ml big bottle shampoo.",
    keywords: ["clinic plus 340ml", "clinic plus big"],
  },
  {
    barcode: "8901030048003",
    name: "Clinic Plus Strong & Long Shampoo Sachet (6ml)",
    brand: "Clinic Plus",
    category: "Hair Care",
    mrp: 1,
    purchasePrice: 0.75,
    wholesalePrice: 0.85,
    unit: "sachet",
    description: "Clinic plus 1 rupee single use shampoo sachet.",
    keywords: ["clinic plus sachet", "pouch", "1 rs shampoo"],
  },
  {
    barcode: "4902430733854",
    name: "Head & Shoulders Anti-Dandruff Smooth & Silky Shampoo 180ml",
    brand: "Head & Shoulders",
    category: "Hair Care",
    mrp: 185,
    purchasePrice: 142,
    wholesalePrice: 160,
    unit: "bottle",
    description: "Clinically proven anti-dandruff smoothing shampoo.",
    keywords: ["head and shoulders", "dandruff", "shampoo", "180ml"],
  },
  {
    barcode: "8901030049017",
    name: "Sunsilk Black Shine Shampoo 180ml",
    brand: "Sunsilk",
    category: "Hair Care",
    mrp: 135,
    purchasePrice: 104,
    wholesalePrice: 118,
    unit: "bottle",
    description: "Amla and pearl complex for long lasting shiny black hair.",
    keywords: ["sunsilk", "black shine", "sunsilk shampoo"],
  },
  {
    barcode: "8901207001017",
    name: "Dabur Amla Hair Oil 180ml",
    brand: "Dabur",
    category: "Hair Care",
    mrp: 95,
    purchasePrice: 74,
    wholesalePrice: 82,
    unit: "bottle",
    description: "Asli amla nourishment for strong, black, long hair.",
    keywords: ["dabur amla", "amla oil", "dabur hair oil"],
  },
  {
    barcode: "8901150001017",
    name: "Bajaj Almond Drops Non-Sticky Hair Oil 190ml",
    brand: "Bajaj",
    category: "Hair Care",
    mrp: 145,
    purchasePrice: 112,
    wholesalePrice: 125,
    unit: "bottle",
    description: "6x vitamin E almond oil for reduced hair fall.",
    keywords: ["bajaj almond", "almond drops", "hair oil"],
  },

  // ==========================================
  // 10. ORAL CARE & DENTAL
  // ==========================================
  {
    barcode: "8901314010529",
    name: "Colgate Strong Teeth Dental Cream 100g",
    brand: "Colgate",
    category: "Oral Care",
    mrp: 62,
    purchasePrice: 48,
    wholesalePrice: 54,
    unit: "tube",
    description: "Calcium and fluoride cavity protection toothpaste.",
    keywords: ["colgate", "toothpaste", "strong teeth", "100g"],
  },
  {
    barcode: "8901314010536",
    name: "Colgate Strong Teeth Dental Cream 200g",
    brand: "Colgate",
    category: "Oral Care",
    mrp: 120,
    purchasePrice: 92,
    wholesalePrice: 105,
    unit: "tube",
    description: "Colgate 200g family pack toothpaste.",
    keywords: ["colgate 200g", "colgate family", "toothpaste"],
  },
  {
    barcode: "8901314010581",
    name: "Colgate MaxFresh Peppermint Ice Gel 150g",
    brand: "Colgate",
    category: "Oral Care",
    mrp: 130,
    purchasePrice: 100,
    wholesalePrice: 112,
    unit: "tube",
    description: "Cooling crystals freshness blue gel toothpaste.",
    keywords: ["colgate maxfresh", "maxfresh", "blue gel", "toothpaste"],
  },
  {
    barcode: "8901030016019",
    name: "Close Up Everfresh Red Hot Gel Toothpaste 150g",
    brand: "Close Up",
    category: "Oral Care",
    mrp: 125,
    purchasePrice: 96,
    wholesalePrice: 108,
    unit: "tube",
    description: "Red hot spicy anti-germ mouthwash infused gel toothpaste.",
    keywords: ["close up", "closeup", "red gel", "toothpaste"],
  },
  {
    barcode: "8904109401010",
    name: "Patanjali Dant Kanti Ayurvedic Toothpaste 100g",
    brand: "Patanjali",
    category: "Oral Care",
    mrp: 55,
    purchasePrice: 42,
    wholesalePrice: 47,
    unit: "tube",
    description: "Natural herbal dental protection with akarkara, neem, and babool.",
    keywords: ["dant kanti", "patanjali toothpaste", "herbal toothpaste"],
  },
  {
    barcode: "8901207002014",
    name: "Dabur Red Ayurvedic Toothpaste 150g",
    brand: "Dabur",
    category: "Oral Care",
    mrp: 98,
    purchasePrice: 76,
    wholesalePrice: 85,
    unit: "tube",
    description: "Laal manjan power with clove oil and pudina for cavity protection.",
    keywords: ["dabur red", "laal toothpaste", "dabur paste"],
  },
  {
    barcode: "8904000900018",
    name: "Vicco Turmeric Ayurvedic Skin Cream 50g",
    brand: "Vicco",
    category: "Skin Care",
    mrp: 95,
    purchasePrice: 74,
    wholesalePrice: 82,
    unit: "tube",
    description: "Pure turmeric and sandalwood oil ayurvedic antiseptic cream.",
    keywords: ["vicco", "turmeric", "skin cream", "ayurvedic", "vicco turmeric"],
  },
  {
    barcode: "8901030046016",
    name: "Glow & Lovely Advanced Multivitamin Cream 50g",
    brand: "Glow & Lovely",
    category: "Skin Care",
    mrp: 120,
    purchasePrice: 92,
    wholesalePrice: 104,
    unit: "tube",
    description: "HD glow multivitamin brightening face cream.",
    keywords: ["glow and lovely", "fair and lovely", "face cream"],
  },
  {
    barcode: "4005808119010",
    name: "Nivea Soft Light Moisturising Cream 100ml Tub",
    brand: "Nivea",
    category: "Skin Care",
    mrp: 180,
    purchasePrice: 138,
    wholesalePrice: 155,
    unit: "tub",
    description: "Jojoba oil and Vitamin E instant refreshing body cream.",
    keywords: ["nivea soft", "nivea cream", "moisturizer"],
  },
  {
    barcode: "8901030046504",
    name: "Vaseline Deep Moisture Body Lotion 200ml",
    brand: "Vaseline",
    category: "Skin Care",
    mrp: 215,
    purchasePrice: 165,
    wholesalePrice: 185,
    unit: "bottle",
    description: "Pure oat extract micro-droplets deep restoring lotion.",
    keywords: ["vaseline", "body lotion", "deep moisture"],
  },

  // ==========================================
  // 11. DETERGENTS & HOUSEHOLD CLEANING
  // ==========================================
  {
    barcode: "8901030005013",
    name: "Surf Excel Easy Wash Detergent Powder 1kg",
    brand: "Surf Excel",
    category: "Household & Cleaning",
    mrp: 145,
    purchasePrice: 114,
    wholesalePrice: 128,
    unit: "packet",
    description: "Fast stain removing laundry detergent powder.",
    keywords: ["surf excel", "detergent", "easy wash", "powder", "1kg", "washing"],
  },
  {
    barcode: "8901030005020",
    name: "Surf Excel Quick Wash Detergent Powder 500g",
    brand: "Surf Excel",
    category: "Household & Cleaning",
    mrp: 80,
    purchasePrice: 62,
    wholesalePrice: 70,
    unit: "packet",
    description: "500g quick stain dissolving detergent powder.",
    keywords: ["surf excel 500g", "detergent", "washing powder"],
  },
  {
    barcode: "8901030005051",
    name: "Surf Excel Matic Front Load Liquid Detergent 1L",
    brand: "Surf Excel",
    category: "Household & Cleaning",
    mrp: 230,
    purchasePrice: 180,
    wholesalePrice: 200,
    unit: "bottle",
    description: "Liquid detergent designed specifically for automatic washing machines.",
    keywords: ["surf excel matic", "liquid detergent", "washing machine"],
  },
  {
    barcode: "4902430720014",
    name: "Ariel Complete Detergent Powder 1kg",
    brand: "Ariel",
    category: "Household & Cleaning",
    mrp: 155,
    purchasePrice: 120,
    wholesalePrice: 135,
    unit: "packet",
    description: "Deep stain removal enzyme active washing powder.",
    keywords: ["ariel", "ariel detergent", "ariel 1kg"],
  },
  {
    barcode: "4902430721011",
    name: "Tide Plus Double Power Detergent Powder Jasmine & Rose 1kg",
    brand: "Tide",
    category: "Household & Cleaning",
    mrp: 125,
    purchasePrice: 98,
    wholesalePrice: 110,
    unit: "packet",
    description: "Extra white bright washing powder with floral fragrance.",
    keywords: ["tide", "tide detergent", "tide 1kg"],
  },
  {
    barcode: "8901030006010",
    name: "Rin Advanced Detergent Bar 250g",
    brand: "Rin",
    category: "Household & Cleaning",
    mrp: 22,
    purchasePrice: 17,
    wholesalePrice: 19.5,
    unit: "piece",
    description: "Bright white fabric washing soap bar.",
    keywords: ["rin", "rin soap", "rin bar", "kapda soap"],
  },
  {
    barcode: "8901030007017",
    name: "Vim Dishwash Liquid Gel Lemon 250ml Bottle",
    brand: "Vim",
    category: "Household & Cleaning",
    mrp: 65,
    purchasePrice: 50,
    wholesalePrice: 56,
    unit: "bottle",
    description: "Degreasing lemon power dishwashing gel.",
    keywords: ["vim", "dishwash", "liquid gel", "lemon", "vim bar"],
  },
  {
    barcode: "8901030007055",
    name: "Vim Dishwash Bar 300g (Tub/Bar)",
    brand: "Vim",
    category: "Household & Cleaning",
    mrp: 30,
    purchasePrice: 23,
    wholesalePrice: 26,
    unit: "piece",
    description: "Vim green lemon dishwashing bar.",
    keywords: ["vim bar", "dishwash bar", "bartan soap"],
  },
  {
    barcode: "8901396001018",
    name: "Harpic Power Plus Toilet Cleaner Original 500ml",
    brand: "Harpic",
    category: "Household & Cleaning",
    mrp: 99,
    purchasePrice: 78,
    wholesalePrice: 87,
    unit: "bottle",
    description: "10x max power disinfectant toilet cleaning liquid.",
    keywords: ["harpic", "toilet cleaner", "bathroom", "500ml"],
  },
  {
    barcode: "8901396002015",
    name: "Lizol Disinfectant Surface & Floor Cleaner Citrus 500ml",
    brand: "Lizol",
    category: "Household & Cleaning",
    mrp: 110,
    purchasePrice: 86,
    wholesalePrice: 96,
    unit: "bottle",
    description: "99.9% germ kill floor disinfectant fragrance cleaner.",
    keywords: ["lizol", "floor cleaner", "disinfectant", "citrus"],
  },
  {
    barcode: "8901396003012",
    name: "Colin Glass and Surface Cleaner 500ml Trigger Spray",
    brand: "Colin",
    category: "Household & Cleaning",
    mrp: 105,
    purchasePrice: 82,
    wholesalePrice: 92,
    unit: "bottle",
    description: "Shine boost glass and window spray cleaner.",
    keywords: ["colin", "glass cleaner", "colin spray"],
  },

  // ==========================================
  // 12. HEALTH & OTC DIGESTION / PAIN
  // ==========================================
  {
    barcode: "8901030384019",
    name: "ENO Fruit Salt Regular Sachet 5g",
    brand: "ENO",
    category: "Health & First Aid",
    mrp: 10,
    purchasePrice: 7.8,
    wholesalePrice: 8.8,
    unit: "sachet",
    description: "Gets to work in 6 seconds against acidity and heartburn.",
    keywords: ["eno", "eno regular", "acidity"],
  },
  {
    barcode: "8901030384026",
    name: "ENO Fruit Salt Lemon Sachet 5g",
    brand: "ENO",
    category: "Health & First Aid",
    mrp: 10,
    purchasePrice: 7.8,
    wholesalePrice: 8.8,
    unit: "sachet",
    description: "Tangy lemon instant acidity relief powder.",
    keywords: ["eno lemon", "eno yellow"],
  },
  {
    barcode: "4902430730013",
    name: "Vicks VapoRub Pain & Cold Relief Balm 25ml",
    brand: "Vicks",
    category: "Health & First Aid",
    mrp: 95,
    purchasePrice: 74,
    wholesalePrice: 82,
    unit: "jar",
    description: "Menthol and eucalyptus soothing balm for cough, blocked nose, and cold.",
    keywords: ["vicks", "vaporub", "balm", "cold relief"],
  },
  {
    barcode: "8901207005015",
    name: "Dabur Honitus Herbal Cough Syrup 100ml",
    brand: "Dabur",
    category: "Health & First Aid",
    mrp: 115,
    purchasePrice: 90,
    wholesalePrice: 100,
    unit: "bottle",
    description: "Non-drowsy honey and tulsi based cough relief.",
    keywords: ["honitus", "dabur cough syrup", "cough syrup"],
  },
  {
    barcode: "8901207006012",
    name: "Dabur Hajmola Chatcola Digestive Tablets 120 Tablets",
    brand: "Dabur",
    category: "Health & First Aid",
    mrp: 65,
    purchasePrice: 50,
    wholesalePrice: 56,
    unit: "bottle",
    description: "Chatpata tasty digestive tablets.",
    keywords: ["hajmola", "dabur hajmola", "digestive"],
  },
];

/**
 * Multi-Result Search for Master Indian Retail Catalog
 */
export function searchIndianRetailCatalog(
  query: string,
  limit: number = 8
): MasterCatalogProduct[] {
  if (!query || !query.trim()) return [];
  const q = query.trim().toLowerCase();
  const digitsOnly = q.replace(/[^0-9]/g, "");

  const results: MasterCatalogProduct[] = [];

  for (const item of INDIAN_RETAIL_CATALOG) {
    if (digitsOnly.length >= 4 && item.barcode && item.barcode.includes(digitsOnly)) {
      results.push(item);
      continue;
    }
    if (item.name.toLowerCase().includes(q)) {
      results.push(item);
      continue;
    }
    if (item.brand.toLowerCase().includes(q)) {
      results.push(item);
      continue;
    }
    if (item.category.toLowerCase().includes(q)) {
      results.push(item);
      continue;
    }
    if (item.keywords && item.keywords.some((k) => k.includes(q) || q.includes(k))) {
      results.push(item);
      continue;
    }
    if (results.length >= limit) break;
  }

  return results.slice(0, limit);
}

/**
 * Instant 0.01s Offline Matcher
 */
export function findInIndianRetailCatalog(queryOrBarcode: string): MasterCatalogProduct | null {
  const matches = searchIndianRetailCatalog(queryOrBarcode, 1);
  return matches.length > 0 ? matches[0] : null;
}
